---
# User configuration.
github_username: ["johnny-hausman", "roguisharcanetrickster", "elephanteleven", "joshAppDev"]

# Location where configuration files will be stored.
config_dir: '/scry-pi'

# Domain names configuration (related services need to be enabled).
domain_name_enable: false
domain_name: 'home.local'
domain_pihole: 'pihole'          # to access pihole via: http://pihole.home.local
domain_grafana: 'grafana'        # to access grafana via: http://grafana.home.local
domain_prometheus: 'prometheus'  # to access prometheus via: http://prometheus.home.local

# Pi-hole configuration.
pihole_enable: true
pihole_hostname: pihole
pihole_timezone: America/Chicago
pihole_password: "change-this-password"

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin"
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.com/;google.com
  - https://github.com/;github.com
  - https://www.netsuite.com/;netsuite.com

# Prometheus configuration.
prometheus_monitor_prometheus: false
prometheus_node_exporter_targets:
  - 'nodeexp:9100'
prometheus_extra_scrape_configs: ''
prometheus_tsdb_retention_time: 90d

# Custom Metrics configuration (Also requires `monitoring_enable`)
custom_metrics_enable: true 
custom_metrics_prometheus_url: "http://prometheus:9090"
custom_metrics_location: "" 
custom_metrics_collection_interval: "5"  # collection interval
custom_metrics_update_interval: "5"
custom_metrics_pghost: "ep-tiny-hat-a1ptewqu-pooler.ap-southeast-1.aws.neon.tech"
custom_metrics_pgdatabase: "neondb"
custom_metrics_pguser: "neondb_owner"
custom_metrics_pgpassword: "your-pg-password"
custom_metrics_pgsslmode: "require"
custom_metrics_pgchannelbinding: "require"

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_plug_enable: false
shelly_plug_hostname: my-shelly-plug-host-or-ip
shelly_plug_http_username: username
shelly_plug_http_password: "password"

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: false
airgradient_sensors:
  # ID Should be limited to no more than 38 characters, in the set a-z.
  - id: livingroom
    ip: "192.168.0.123"
    port: 9925

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false
